"""
AI Trading Terminal — backend v2
================================
Key changes vs. the previous version:
  * A single block of code (the previous file had EVERYTHING duplicated).
  * Alpaca client with a reusable session, explicit `start`, pagination,
    the /snapshots endpoint (1 request for the whole watchlist) and a feed
    fallback.
  * Synthetic data is flagged as such and is NEVER presented to the LLM as if
    it were real.
  * Indicators (SMA/EMA/RSI/ATR/vol/drawdown) are computed in Python.
    The LLM interprets, it does not calculate. This is what fixes "accuracy".
  * One LLM call per turn (it used to be 3 chained) + conversation memory +
    JSON mode => faster and more consistent.
  * Projections are generated by Python from real volatility; the model only
    picks scenario and horizon. LLMs cannot do arithmetic.
  * SSE (/api/stream) + background poller => the UI updates itself.

Run:
    pip install -r requirements.txt
    python app.py
"""

from __future__ import annotations

import json
import math
import os
import queue
import re
import threading
import time
import warnings
from collections import deque
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta, timezone
from typing import Any

import feedparser
import requests
import urllib3
from flask import Flask, Response, jsonify, request, stream_with_context

# --------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------
# Loads the .env sitting next to this file. Without it every variable stays
# empty and Alpaca answers 401.
try:
    from dotenv import load_dotenv

    load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))
except ImportError:  # minimal fallback if python-dotenv is missing
    _env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    if os.path.exists(_env_path):
        with open(_env_path, encoding="utf-8") as _f:
            for _line in _f:
                _line = _line.strip()
                if _line and not _line.startswith("#") and "=" in _line:
                    _k, _v = _line.split("=", 1)
                    os.environ.setdefault(_k.strip(), _v.strip().strip("\"'"))

os.environ["OTEL_SDK_DISABLED"] = "true"
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
warnings.filterwarnings("ignore", module="urllib3")

# TCS corporate proxy: instead of patching requests globally (which affected
# EVERY library, including the LLM SDK), we use a dedicated session.
VERIFY_SSL = os.environ.get("VERIFY_SSL", "0") == "1"

ALPACA_KEY_ID = os.environ.get("ALPACA_KEY_ID", "")
ALPACA_SECRET_KEY = os.environ.get("ALPACA_SECRET_KEY", "")
ALPACA_DATA_URL = os.environ.get("ALPACA_DATA_URL", "https://data.alpaca.markets/v2")
ALPACA_FEED = os.environ.get("ALPACA_FEED", "iex")  # iex = free, sip = paid

LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "https://genailab.tcs.in")
LLM_API_KEY = os.environ.get("LLM_API_KEY", "")
LLM_MODEL = os.environ.get("LLM_MODEL", "azure/genailab-maas-gpt-4.1")

ALPACA_TRADING_URL = os.environ.get("ALPACA_TRADING_URL", "https://paper-api.alpaca.markets/v2")

ELEVEN_API_KEY = os.environ.get("ELEVENLABS_API_KEY", "")
ELEVEN_AGENT_ID = os.environ.get("ELEVENLABS_AGENT_ID", "")
# Default voice for local mode (no agent required). Daniel: deep, stable.
ELEVEN_VOICE_ID = os.environ.get("ELEVENLABS_VOICE_ID", "6OzrBCQf8cjERkYgzSg8")
# auto = try ElevenLabs, fall back to the browser engine on failure
# browser = never call ElevenLabs (free, unlimited, lower quality)
# elevenlabs = ElevenLabs only, no fallback
TTS_PROVIDER = os.environ.get("TTS_PROVIDER", "auto").lower()

DEFAULT_SYMBOLS = ["AAPL", "MSFT", "SPY", "TSLA", "NVDA"]
POLL_SECONDS = int(os.environ.get("POLL_SECONDS", 5))

app = Flask(__name__)
_pool = ThreadPoolExecutor(max_workers=8)

# --------------------------------------------------------------------------
# Cache with per-datatype TTL
# --------------------------------------------------------------------------
_cache: dict[str, dict] = {}
_cache_lock = threading.Lock()

TTL = {"snapshot": 3, "bars_intraday": 30, "bars_daily": 300, "news": 180}


def cache_get(key: str):
    with _cache_lock:
        e = _cache.get(key)
        if e and (time.time() - e["t"]) < e["ttl"]:
            return e["v"]
    return None


def cache_set(key: str, value, ttl: int = 30):
    with _cache_lock:
        _cache[key] = {"t": time.time(), "v": value, "ttl": ttl}


# --------------------------------------------------------------------------
# Alpaca client
# --------------------------------------------------------------------------
_alpaca = requests.Session()
_alpaca.verify = VERIFY_SSL
_alpaca.headers.update(
    {
        "APCA-API-KEY-ID": ALPACA_KEY_ID,
        "APCA-API-SECRET-KEY": ALPACA_SECRET_KEY,
        "Accept": "application/json",
    }
)
_alpaca.mount(
    "https://",
    requests.adapters.HTTPAdapter(pool_connections=10, pool_maxsize=20, max_retries=0),
)

# How much history to request per timeframe. Alpaca ignores `limit` without a
# coherent `start` and returns stale data: this was a direct cause of the AI
# analyzing prices that were not current.
LOOKBACK = {
    "1Min": timedelta(days=5),
    "5Min": timedelta(days=15),
    "15Min": timedelta(days=45),
    "1Hour": timedelta(days=180),
    "1Day": timedelta(days=800),
    "1Week": timedelta(days=2500),
    "1Month": timedelta(days=5000),
}
INTRADAY = {"1Min", "5Min", "15Min", "1Hour"}


def _alpaca_get(path: str, params: dict, timeout: float = 8.0) -> dict:
    """GET with one retry and backoff on 429/5xx."""
    url = f"{ALPACA_DATA_URL}{path}"
    last_exc = None
    for attempt in range(2):
        try:
            r = _alpaca.get(url, params=params, timeout=timeout)
            if r.status_code in (429, 500, 502, 503):
                raise requests.HTTPError(f"HTTP {r.status_code}")
            r.raise_for_status()
            return r.json()
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            if attempt == 0:
                time.sleep(0.6)
    raise last_exc  # type: ignore[misc]


def _norm_bars(raw: list[dict], daily: bool) -> list[dict]:
    return [
        {
            "time": b["t"][:10] if daily else b["t"],
            "open": b["o"],
            "high": b["h"],
            "low": b["l"],
            "close": b["c"],
            "volume": b["v"],
        }
        for b in raw
    ]


def get_bars(symbol: str, timeframe: str = "1Day", limit: int = 250) -> dict:
    """Returns {'bars': [...], 'source': 'alpaca'|'synthetic', 'feed': ..., 'stale': bool}.

    Bars are requested in DESCENDING order and reversed afterwards. Ascending +
    an early break returned the OLDEST window instead of the newest one, which
    is what made the chart show year-old prices.

    'source' travels all the way to the LLM prompt and the UI, so a "real"
    analysis is never presented on top of invented data.
    """
    tf = timeframe if timeframe in LOOKBACK else "1Day"
    daily = tf not in INTRADAY
    ttl = TTL["bars_daily"] if daily else TTL["bars_intraday"]
    key = f"bars:{symbol}:{tf}:{limit}"
    if (hit := cache_get(key)) is not None:
        return hit

    start = (datetime.now(timezone.utc) - LOOKBACK[tf]).strftime("%Y-%m-%dT%H:%M:%SZ")
    collected: list[dict] = []
    page_token = None

    try:
        for _ in range(5):  # up to 5 pages
            params = {
                "symbols": symbol,
                "timeframe": tf,
                "start": start,
                "limit": min(limit, 10000),
                "feed": ALPACA_FEED,
                "adjustment": "split",  # 'raw' breaks split-adjusted series (NVDA, TSLA)
                "sort": "desc",         # newest first, so an early break keeps recent data
            }
            if page_token:
                params["page_token"] = page_token
            data = _alpaca_get("/stocks/bars", params)
            collected.extend(data.get("bars", {}).get(symbol, []))
            page_token = data.get("next_page_token")
            if not page_token or len(collected) >= limit:
                break

        if not collected:
            raise ValueError("no bars")

        collected = collected[:limit]
        collected.reverse()                     # back to chronological order
        bars = _norm_bars(collected, daily)

        # Sanity check: if the newest bar is old, say so instead of pretending.
        age_days = None
        try:
            last_dt = datetime.fromisoformat(bars[-1]["time"][:10])
            age_days = (datetime.now(timezone.utc).date() - last_dt.date()).days
        except Exception:  # noqa: BLE001
            pass
        stale = bool(age_days is not None and age_days > (7 if daily else 3))
        if stale:
            app.logger.warning("%s %s: newest bar is %d days old (feed=%s)",
                               symbol, tf, age_days, ALPACA_FEED)

        out = {"bars": bars, "source": "alpaca", "feed": ALPACA_FEED, "symbol": symbol,
               "stale": stale, "age_days": age_days}
        cache_set(key, out, ttl)
        return out

    except Exception as exc:  # noqa: BLE001
        app.logger.warning("Alpaca bars %s/%s failed: %s", symbol, tf, exc)
        out = {
            "bars": _synthetic_bars(symbol, min(limit, 250)),
            "source": "synthetic",
            "feed": None,
            "symbol": symbol,
            "stale": True,
            "error": str(exc)[:180],
        }
        cache_set(key, out, 30)
        return out


def get_snapshots(symbols: list[str]) -> dict[str, dict]:
    """ONE request for the whole watchlist (it used to be one per symbol).

    It also returns the previous close, so the % change is the real daily one
    and not the difference between the last two candles.
    """
    symbols = [s.upper() for s in symbols if s]
    if not symbols:
        return {}
    key = "snap:" + ",".join(sorted(symbols))
    if (hit := cache_get(key)) is not None:
        return hit

    out: dict[str, dict] = {}
    try:
        data = _alpaca_get(
            "/stocks/snapshots", {"symbols": ",".join(symbols), "feed": ALPACA_FEED}
        )
        raw = data.get("snapshots", data)
        for sym in symbols:
            s = raw.get(sym) or {}
            trade = s.get("latestTrade") or {}
            quote = s.get("latestQuote") or {}
            day = s.get("dailyBar") or {}
            prev = s.get("prevDailyBar") or {}
            price = trade.get("p") or quote.get("ap") or quote.get("bp") or day.get("c")
            base = prev.get("c") or day.get("o")
            if not price:
                continue
            chg = (price - base) if base else 0.0
            snap_out = {
                "symbol": sym,
                "price": round(float(price), 2),
                "change": round(chg, 2),
                "change_pct": round((chg / base * 100) if base else 0.0, 2),
                "source": "alpaca",
            }
            for k, v in (("day_high", day.get("h")), ("day_low", day.get("l")),
                         ("volume", day.get("v")), ("time", trade.get("t") or quote.get("t"))):
                if v:
                    snap_out[k] = v
            out[sym] = snap_out
    except Exception as exc:  # noqa: BLE001
        app.logger.warning("Alpaca snapshots failed: %s", exc)

    # Fill in the ones that did not come back
    for sym in symbols:
        if sym not in out:
            b = get_bars(sym, limit=2)
            bars = b["bars"]
            last = bars[-1]["close"] if bars else 0.0
            prev_c = bars[-2]["close"] if len(bars) > 1 else last
            out[sym] = {
                "symbol": sym,
                "price": round(last, 2),
                "change": round(last - prev_c, 2),
                "change_pct": round(((last - prev_c) / prev_c * 100) if prev_c else 0, 2),
                "source": b["source"],
            }

    cache_set(key, out, TTL["snapshot"])
    return out


def _synthetic_bars(symbol: str, limit: int) -> list[dict]:
    import random

    rnd = random.Random(sum(ord(c) for c in symbol))
    price = float(50 + (sum(ord(c) for c in symbol) % 400))
    bars, today = [], datetime.now(timezone.utc).date()
    for i in range(limit, 0, -1):
        price = max(1.0, price * (1 + rnd.uniform(-0.015, 0.017)))
        o = price * (1 + rnd.uniform(-0.004, 0.004))
        c = price * (1 + rnd.uniform(-0.004, 0.004))
        bars.append(
            {
                "time": (today - timedelta(days=i)).isoformat(),
                "open": round(o, 2),
                "high": round(max(o, c) * 1.004, 2),
                "low": round(min(o, c) * 0.996, 2),
                "close": round(c, 2),
                "volume": rnd.randint(1_000_000, 20_000_000),
            }
        )
    return bars


# --------------------------------------------------------------------------
# Indicators — computed in Python, NOT by the LLM
# --------------------------------------------------------------------------
def _sma(v: list[float], n: int):
    return round(sum(v[-n:]) / n, 2) if len(v) >= n else None


def _ema(v: list[float], n: int):
    if len(v) < n:
        return None
    k, e = 2 / (n + 1), sum(v[:n]) / n
    for x in v[n:]:
        e = x * k + e * (1 - k)
    return round(e, 2)


def _rsi(v: list[float], n: int = 14):
    if len(v) < n + 1:
        return None
    gains = losses = 0.0
    for i in range(-n, 0):
        d = v[i] - v[i - 1]
        gains += max(d, 0)
        losses += max(-d, 0)
    if losses == 0:
        return 100.0
    rs = (gains / n) / (losses / n)
    return round(100 - 100 / (1 + rs), 1)


def _atr_pct(bars: list[dict], n: int = 14):
    if len(bars) < n + 1:
        return None
    trs = []
    for i in range(-n, 0):
        h, l, pc = bars[i]["high"], bars[i]["low"], bars[i - 1]["close"]
        trs.append(max(h - l, abs(h - pc), abs(l - pc)))
    atr = sum(trs) / n
    return round(atr / bars[-1]["close"] * 100, 2)


def compute_analysis(symbol: str, timeframe: str = "1Day") -> dict:
    """Only fields with an actual value are returned.

    Anything the data does not support is omitted entirely rather than sent as
    null: an empty slot in the UI and a null in the prompt both invite the model
    to talk about something it does not know.
    """
    payload = get_bars(symbol, timeframe=timeframe, limit=250)
    bars = payload["bars"]
    closes = [b["close"] for b in bars]
    if not closes:
        return {"symbol": symbol, "error": "no data"}

    def pct(n: int):
        if len(closes) <= n or not closes[-n - 1]:
            return None
        return round((closes[-1] / closes[-n - 1] - 1) * 100, 2)

    rets = [
        closes[i] / closes[i - 1] - 1
        for i in range(max(1, len(closes) - 60), len(closes))
        if closes[i - 1]
    ]
    mean = sum(rets) / len(rets) if rets else 0.0
    var = sum((r - mean) ** 2 for r in rets) / len(rets) if rets else 0.0
    daily_vol = math.sqrt(var)

    window = closes[-252:]
    hi, lo = max(window), min(window)
    sma20, sma50 = _sma(closes, 20), _sma(closes, 50)

    changes = {k: v for k, v in
               {"1d": pct(1), "5d": pct(5), "20d": pct(20), "60d": pct(60)}.items()
               if v is not None}

    vols = [b["volume"] for b in bars[-20:] if b.get("volume")]
    rel_vol = (round(bars[-1]["volume"] / (sum(vols) / len(vols)), 2)
               if len(vols) == 20 and bars[-1].get("volume") else None)

    out = {
        "symbol": symbol,
        "timeframe": timeframe,
        "data_source": payload["source"],
        "as_of": bars[-1]["time"],
        "bars_available": len(bars),
        "last_close": closes[-1],
    }
    if payload.get("feed"):
        out["feed"] = payload["feed"]
    if payload.get("stale"):
        out["stale"] = True
        if payload.get("age_days") is not None:
            out["days_since_last_bar"] = payload["age_days"]
    if changes:
        out["change_pct"] = changes
    if sma20:
        out["sma20"] = sma20
        out["price_vs_sma20_pct"] = round((closes[-1] / sma20 - 1) * 100, 2)
    if sma50:
        out["sma50"] = sma50
    if sma20 and sma50:
        out["trend"] = "uptrend" if sma20 > sma50 else "downtrend"
    if (ema := _ema(closes, 12)) is not None:
        out["ema12"] = ema
    if (rsi := _rsi(closes)) is not None:
        out["rsi14"] = rsi
    if (atr := _atr_pct(bars)) is not None:
        out["atr14_pct"] = atr
    if rets:
        out["annualized_vol_pct"] = round(daily_vol * math.sqrt(252) * 100, 1)
        out["daily_vol_pct"] = round(daily_vol * 100, 2)
    if hi > lo:
        out["range_52w"] = {"high": round(hi, 2), "low": round(lo, 2)}
        out["pos_in_52w_range_pct"] = round((closes[-1] - lo) / (hi - lo) * 100, 1)
    if rel_vol is not None:
        out["relative_volume"] = rel_vol

    out["_bars"] = bars
    return out


# --------------------------------------------------------------------------
# Projections — deterministic, computed in Python
# --------------------------------------------------------------------------
def build_projection(
    bars: list[dict], days: int = 10, scenario: str = "base", shock_pct: float = 0.0
) -> list[dict]:
    """Projected path from the REAL drift and volatility.

    'bull'/'bear' = base drift ± daily sigma. The initial shock models what-ifs
    ("what if it drops 10% on an earnings miss?").
    """
    if not bars:
        return []
    closes = [b["close"] for b in bars]
    rets = [closes[i] / closes[i - 1] - 1 for i in range(1, len(closes)) if closes[i - 1]][-60:]
    mu = sum(rets) / len(rets) if rets else 0.0
    sd = (
        math.sqrt(sum((r - mu) ** 2 for r in rets) / len(rets)) if len(rets) > 1 else 0.01
    )
    drift = {"base": mu, "bull": mu + sd * 0.6, "bear": mu - sd * 0.6}.get(scenario, mu)
    drift = max(min(drift, 0.02), -0.02)  # sanity cap

    try:
        last_date = datetime.fromisoformat(bars[-1]["time"][:10])
    except Exception:  # noqa: BLE001
        last_date = datetime.now()

    price = closes[-1] * (1 + shock_pct / 100.0)
    pts, added = [], 0
    i = 1
    while added < days and i < days * 3:
        d = last_date + timedelta(days=i)
        i += 1
        if d.weekday() >= 5:  # skip weekends: the chart used to break
            continue
        price *= 1 + drift
        pts.append({"time": d.date().isoformat(), "value": round(price, 2)})
        added += 1
    return pts


# --------------------------------------------------------------------------
# News
# --------------------------------------------------------------------------
def get_news(symbol: str | None = None, limit: int = 12) -> list[dict]:
    key = f"news:{symbol or 'market'}"
    if (hit := cache_get(key)) is not None:
        return hit
    sym = symbol or "%5EGSPC"
    url = f"https://feeds.finance.yahoo.com/rss/2.0/headline?s={sym}&region=US&lang=en-US"
    items = []
    try:
        for e in feedparser.parse(url).entries[:limit]:
            items.append(
                {
                    "title": e.get("title", ""),
                    "link": e.get("link", ""),
                    "published": e.get("published", ""),
                    "summary": re.sub("<[^<]+?>", "", e.get("summary", ""))[:220],
                    "source": "Yahoo Finance",
                }
            )
    except Exception as exc:  # noqa: BLE001
        app.logger.warning("News fetch failed: %s", exc)
    if not items:
        items = [{"title": f"No headlines available for {symbol or 'the market'}.", "link": "",
                  "published": "", "summary": "", "source": "system"}]
    cache_set(key, items, TTL["news"])
    return items


def filter_news_by_keywords(items, keywords):
    if not keywords:
        return items
    kw = [k.lower() for k in keywords]
    f = [i for i in items if any(k in (i["title"] + " " + i["summary"]).lower() for k in kw)]
    return f or items


# --------------------------------------------------------------------------
# AI layer
# --------------------------------------------------------------------------
SYSTEM_PROMPT = """You are the analyst on a live trading desk, talking to a colleague
who is looking at the same screen. You are a person, not a data readout.

## Read the intent first
Not every message is a market question. Match the register:

- Greeting or small talk ("hi", "how's it going", "thanks"): answer like a human,
  one warm line, NO numbers, NO ticker. Then offer one concrete thing you could
  do next. Example: "Morning. Want me to run through the watchlist and flag
  what's moved?"
- Vague or open ("what's up", "anything interesting", "what should I look at"):
  do NOT default to the active symbol. Use the watchlist scan you were given and
  lead with the single most notable thing.
- Named symbol or explicit market question: give the read. Two or three
  sentences, numbers in each.

## When you give a market read
Every sentence carries a number from the metrics. If a sentence has no number,
delete it. Never recalculate, never invent. Fields that are absent were not
computable: don't mention them, don't speculate, don't apologize.

If `data_source` is "synthetic" or `stale` is true, say so in five words first,
then give no directional call.

## Recommend without being asked
You are the assistant. Do not wait to be interrogated. When you have a `recommendation`
block, use it: state the bias, the conviction, the two strongest signals behind it,
and the stop level. Tie the news tone in when it is positive or negative. Close with
a concrete next step you could take — but if that step changes the screen (projection,
watchlist edit, symbol change), ASK before doing it.

Never present a recommendation as certainty. "Leaning bullish" not "it will go up".
This is paper trading and you are not a financial advisor — say that once per session
at most, never repeatedly.

## Output
Valid JSON only:
{ "reply": "<match the register above>", "commands": [ ... ] }

Commands (only when they add something; empty is normal):
  {"action":"add_projection","scenario":"base|bull|bear","days":10,"label":"..."}
  {"action":"add_scenario","scenario":"base|bull|bear","days":10,"shock_pct":-8,"label":"Earnings miss"}
  {"action":"add_overlay","symbol":"MSFT"}
  {"action":"remove_overlay","symbol":"MSFT"}
  {"action":"set_symbol","symbol":"AAPL"}
  {"action":"search_symbol","query":"nvidia"}
  {"action":"add_watchlist","symbol":"NVDA"}
  {"action":"remove_watchlist","symbol":"TSLA"}
  {"action":"load_news","topic":"semiconductors"}
  {"action":"open_news","index":3}
  {"action":"filter_news","keywords":["fed","rates"]}
  {"action":"clear_projections"}
  {"action":"focus_panel","panel":"chart|news|watchlist|chat|balanced"}
  {"action":"toggle_indicator","indicator":"sma20|sma50|ema12|bollinger|vwap|rsi|fib|levels|volume|logscale","on":true}

If the user names a company rather than a ticker ("add nvidia", "pull up apple"),
emit search_symbol with what they said — the server resolves it.

Never write out price lists: the server computes curves from real volatility.
You pick scenario, horizon and shock only.

## Examples
User: "hey" -> "Hey. Markets are open — want me to scan the watchlist and tell you
what's actually moved?"
User: "how does nvidia look" -> "NVDA at 178.40, RSI 71 and 4.2% over its 20-day, so
it's stretched. Headlines are positive but I'd lean neutral here; ATR is 3.1%, which
puts a sensible stop under 172."
"""

_sessions: dict[str, deque] = {}
_sessions_lock = threading.Lock()


def _history(session_id: str) -> deque:
    with _sessions_lock:
        return _sessions.setdefault(session_id, deque(maxlen=8))


def _llm_client():
    from openai import OpenAI
    import httpx

    return OpenAI(
        base_url=LLM_BASE_URL,
        api_key=LLM_API_KEY,
        http_client=httpx.Client(verify=VERIFY_SSL, timeout=25.0),
        max_retries=1,
    )


_llm_singleton = None
_llm_lock = threading.Lock()


def llm_client():
    global _llm_singleton
    with _llm_lock:
        if _llm_singleton is None:
            _llm_singleton = _llm_client()
    return _llm_singleton


def _extract_json(text: str):
    text = re.sub(r"^```(json)?|```$", "", text.strip()).strip()
    try:
        return json.loads(text)
    except Exception:  # noqa: BLE001
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if m:
            try:
                return json.loads(m.group(0))
            except Exception:  # noqa: BLE001
                return None
    return None


def ask_ai(message: str, symbol: str, session_id: str = "default") -> dict:
    t0 = time.time()

    # Context in parallel: analysis + news at once, not sequentially.
    f_analysis = _pool.submit(compute_analysis, symbol)
    f_news = _pool.submit(get_news, symbol, 6)
    f_rec = _pool.submit(build_recommendation, symbol)
    f_brief = _pool.submit(build_briefing, sorted(_tracked)[:6])
    analysis = f_analysis.result()
    bars = analysis.pop("_bars", [])
    headlines = [n["title"] for n in f_news.result()[:5]]

    rec = f_rec.result()
    rec.pop("as_of", None)
    ctx = {**analysis, "recent_headlines": headlines,
           "recommendation": {k: v for k, v in rec.items() if k not in ("symbol",)},
           "watchlist_scan": f_brief.result().get("alerts", [])}
    hist = _history(session_id)

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages += list(hist)
    messages.append(
        {
            "role": "user",
            "content": f"METRICS ({symbol}):\n{json.dumps(ctx, ensure_ascii=False)}\n\nUser: {message}",
        }
    )

    parsed = None
    try:
        completion = llm_client().chat.completions.create(
            model=LLM_MODEL,
            messages=messages,
            temperature=0.1,          # was 0.4: structured output kept breaking
            max_tokens=300,
            response_format={"type": "json_object"},
        )
        parsed = _extract_json(completion.choices[0].message.content or "")
    except Exception as exc:  # noqa: BLE001
        app.logger.warning("LLM call failed: %s", exc)

    if not parsed or "reply" not in parsed:
        parsed = _fallback(analysis, message)

    # The server materializes commands: the model never generates prices.
    commands = []
    for c in parsed.get("commands", [])[:4]:
        a = c.get("action")
        if a in ("add_projection", "add_scenario"):
            pts = build_projection(
                bars,
                days=int(c.get("days") or 10),
                scenario=str(c.get("scenario") or "base"),
                shock_pct=float(c.get("shock_pct") or 0),
            )
            if pts:
                commands.append(
                    {"action": a, "symbol": symbol, "label": c.get("label") or "AI Projection",
                     "points": pts}
                )
        elif a == "search_symbol":
            hits = search_assets(c.get("query", ""), 5)
            if hits:
                commands.append({"action": "search_results", "query": c.get("query"),
                                 "results": hits})
        elif a in ("add_overlay", "remove_overlay", "set_symbol", "filter_news",
                   "clear_projections", "load_news", "open_news",
                   "add_watchlist", "remove_watchlist", "focus_panel",
                   "toggle_indicator"):
            commands.append(c)

    hist.append({"role": "user", "content": message[:400]})
    hist.append({"role": "assistant", "content": parsed["reply"][:400]})

    return {
        "reply": parsed["reply"],
        "commands": commands,
        "metrics": {k: v for k, v in analysis.items() if not k.startswith("_")},
        "latency_ms": int((time.time() - t0) * 1000),
    }


def _fallback(a: dict, message: str) -> dict:
    """Deterministic answer when the LLM is unavailable: uses the same indicators,
    so the demo never looks broken."""
    if a.get("error"):
        return {"reply": f"No market data available for {a.get('symbol')}.", "commands": []}
    rsi = a.get("rsi14")
    tone = "overbought" if rsi and rsi > 70 else "oversold" if rsi and rsi < 30 else "neutral"
    scen = "bull" if a.get("trend") == "uptrend" else "bear"
    rsi = rsi if rsi is not None else "n/a"
    return {
        "reply": (
            f"{a['symbol']} at {a['last_close']}, RSI {rsi} ({tone}). "
            f"{scen.capitalize()} projection plotted."
        ),
        "commands": [{"action": "add_projection", "scenario": scen, "days": 10,
                      "label": f"{scen.capitalize()} projection"}],
    }


# --------------------------------------------------------------------------
# Live stream (SSE) + background poller
# --------------------------------------------------------------------------
_subscribers: list[queue.Queue] = []
_subs_lock = threading.Lock()
_tracked: set[str] = set(DEFAULT_SYMBOLS)
_last_sent: dict[str, float] = {}


def _broadcast(event: str, payload: dict):
    msg = f"event: {event}\ndata: {json.dumps(payload)}\n\n"
    with _subs_lock:
        for q in list(_subscribers):
            try:
                q.put_nowait(msg)
            except queue.Full:
                pass


def _poller():
    while True:
        try:
            with _subs_lock:
                active = bool(_subscribers)
            if active and _tracked:
                snaps = get_snapshots(sorted(_tracked))
                changed = {
                    s: v for s, v in snaps.items()
                    if _last_sent.get(s) != v["price"]
                }
                if changed:
                    _last_sent.update({s: v["price"] for s, v in changed.items()})
                    _broadcast("quotes", {"quotes": list(changed.values()),
                                          "ts": datetime.now(timezone.utc).isoformat()})
        except Exception as exc:  # noqa: BLE001
            app.logger.warning("poller: %s", exc)
        time.sleep(POLL_SECONDS)


threading.Thread(target=_poller, daemon=True).start()


@app.route("/api/stream")
def api_stream():
    symbols = request.args.get("symbols", ",".join(DEFAULT_SYMBOLS))
    _tracked.update(s.strip().upper() for s in symbols.split(",") if s.strip())
    q: queue.Queue = queue.Queue(maxsize=50)
    with _subs_lock:
        _subscribers.append(q)

    @stream_with_context
    def gen():
        try:
            yield "retry: 3000\n\n"
            snaps = get_snapshots(sorted(_tracked))
            yield f"event: quotes\ndata: {json.dumps({'quotes': list(snaps.values())})}\n\n"
            while True:
                try:
                    yield q.get(timeout=15)
                except queue.Empty:
                    yield ": keepalive\n\n"
        finally:
            with _subs_lock:
                if q in _subscribers:
                    _subscribers.remove(q)

    return Response(gen(), mimetype="text/event-stream",
                    headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


# --------------------------------------------------------------------------
# Instrument search (Alpaca /v2/assets)
# --------------------------------------------------------------------------
# Alpaca has no search endpoint: the universe is downloaded once (~11k assets)
# and matched locally. Instant, and works offline.
_assets: list[dict] = []
_assets_lock = threading.Lock()


def load_assets(force: bool = False) -> list[dict]:
    global _assets
    with _assets_lock:
        if _assets and not force:
            return _assets
    try:
        r = _alpaca.get(
            f"{ALPACA_TRADING_URL}/assets",
            params={"status": "active", "asset_class": "us_equity"},
            timeout=25,
        )
        r.raise_for_status()
        data = [
            {
                "symbol": a["symbol"],
                "name": a.get("name") or a["symbol"],
                "exchange": a.get("exchange"),
                "etf": bool(a.get("attributes") and "etf" in str(a.get("attributes")).lower()),
                "tradable": a.get("tradable", False),
            }
            for a in r.json()
            if a.get("tradable") and a.get("exchange") in ("NASDAQ", "NYSE", "ARCA", "AMEX", "BATS")
        ]
        with _assets_lock:
            _assets = data
        app.logger.info("Alpaca universe loaded: %d assets", len(data))
    except Exception as exc:  # noqa: BLE001
        if "401" in str(exc):
            app.logger.error(
                "/assets returned 401: your Alpaca keys are empty or not valid for %s. "
                "Check ALPACA_KEY_ID / ALPACA_SECRET_KEY in your .env "
                "(current key starts with %r).",
                ALPACA_TRADING_URL,
                (ALPACA_KEY_ID[:4] + "…") if ALPACA_KEY_ID else "EMPTY",
            )
        else:
            app.logger.warning("Could not load /assets: %s", exc)
    return _assets


def search_assets(query: str, limit: int = 8) -> list[dict]:
    """Ranking: exact ticker > ticker starts with > name starts with > name
    contains. So 'apple' returns AAPL and 'micro' puts MSFT on top."""
    q = (query or "").strip().upper()
    if not q:
        return []
    assets = load_assets()
    if not assets:
        # With no universe (401 or network down) we still accept exact tickers:
        # search loses name matching, but the app keeps working.
        snap = get_snapshots([q]).get(q)
        if snap and snap.get("source") == "alpaca":
            return [{"symbol": q, "name": q, "exchange": "?", "etf": False, "tradable": True}]
        return []
    scored = []
    for a in assets:
        sym, name = a["symbol"], a["name"].upper()
        if sym == q:
            s = 0
        elif sym.startswith(q):
            s = 1
        elif name.startswith(q):
            s = 2
        elif q in name:
            s = 3
        elif q in sym:
            s = 4
        else:
            continue
        scored.append((s, len(sym), a))
    scored.sort(key=lambda x: (x[0], x[1]))
    return [a for _, _, a in scored[:limit]]


# --------------------------------------------------------------------------
# Topic-based news (Google News RSS) in addition to per-symbol
# --------------------------------------------------------------------------
def get_news_by_topic(topic: str, limit: int = 12) -> list[dict]:
    key = f"news:topic:{topic.lower()}"
    if (hit := cache_get(key)) is not None:
        return hit
    from urllib.parse import quote_plus

    url = (
        "https://news.google.com/rss/search?q="
        + quote_plus(f"{topic} stock market finance")
        + "&hl=en-US&gl=US&ceid=US:en"
    )
    items = []
    try:
        for e in feedparser.parse(url).entries[:limit]:
            items.append(
                {
                    "title": e.get("title", ""),
                    "link": e.get("link", ""),
                    "published": e.get("published", ""),
                    "summary": re.sub("<[^<]+?>", "", e.get("summary", ""))[:220],
                    "source": (e.get("source", {}) or {}).get("title", "Google News"),
                    "topic": topic,
                }
            )
    except Exception as exc:  # noqa: BLE001
        app.logger.warning("Topic news fetch failed: %s", exc)
    if items:
        cache_set(key, items, TTL["news"])
    return items


def extract_article(url: str) -> dict:
    """Best-effort article body extraction, so the agent can explain it by voice
    instead of just reading the headline."""
    key = f"art:{url}"
    if (hit := cache_get(key)) is not None:
        return hit
    out = {"url": url, "text": "", "title": ""}
    try:
        r = requests.get(
            url,
            timeout=10,
            verify=VERIFY_SSL,
            headers={"User-Agent": "Mozilla/5.0 (compatible; TradingTerminal/1.0)"},
        )
        html = r.text
        m = re.search(r"<title[^>]*>(.*?)</title>", html, re.S | re.I)
        out["title"] = re.sub(r"\s+", " ", m.group(1)).strip() if m else ""
        body = re.sub(r"(?s)<(script|style|nav|footer|header|aside)[^>]*>.*?</\1>", " ", html)
        paras = re.findall(r"(?s)<p[^>]*>(.*?)</p>", body)
        text = " ".join(re.sub("<[^>]+>", "", p) for p in paras)
        text = re.sub(r"&[a-z]+;", " ", text)
        out["text"] = re.sub(r"\s+", " ", text).strip()[:4000]
    except Exception as exc:  # noqa: BLE001
        out["error"] = str(exc)[:150]
    cache_set(key, out, 900)
    return out


# Preload the instrument universe. It goes here, not higher up: load_assets must
# already be defined when the thread starts.
threading.Thread(target=load_assets, daemon=True).start()


# --------------------------------------------------------------------------
# API routes
# --------------------------------------------------------------------------
@app.route("/api/search")
def api_search():
    return jsonify(search_assets(request.args.get("q", ""), int(request.args.get("limit", 8))))


@app.route("/api/article")
def api_article():
    url = request.args.get("url", "")
    if not url.startswith("http"):
        return jsonify({"error": "invalid url"}), 400
    return jsonify(extract_article(url))


@app.route("/api/voice/token")
def api_voice_token():
    """Mints the WebRTC token server-side: the ElevenLabs API key never reaches
    the browser."""
    if not ELEVEN_API_KEY or not ELEVEN_AGENT_ID:
        return jsonify({"error": "Missing ELEVENLABS_API_KEY or ELEVENLABS_AGENT_ID"}), 503
    try:
        r = requests.get(
            "https://api.elevenlabs.io/v1/convai/conversation/token",
            params={"agent_id": ELEVEN_AGENT_ID},
            headers={"xi-api-key": ELEVEN_API_KEY},
            timeout=12,
            verify=VERIFY_SSL,
        )
        r.raise_for_status()
        return jsonify(r.json())
    except Exception as exc:  # noqa: BLE001
        app.logger.warning("ElevenLabs token: %s", exc)
        return jsonify({"error": str(exc)[:200]}), 502


@app.route("/api/voice/mode")
def api_voice_mode():
    """Tells the frontend which voice mode is available.

    'agent' = ElevenLabs Agents platform (needs ELEVENLABS_AGENT_ID).
    'local' = browser STT + your own LLM + ElevenLabs TTS. API key only.
    """
    tts = TTS_PROVIDER
    if not ELEVEN_API_KEY and tts != "browser":
        tts = "browser"      # no key: the browser engine is the only option
    if ELEVEN_API_KEY and ELEVEN_AGENT_ID.startswith("agent_") and tts != "browser":
        return jsonify({"mode": "agent", "tts": tts})
    # Local mode works with no ElevenLabs key at all when tts == browser.
    return jsonify({"mode": "local", "tts": tts, "voice_id": ELEVEN_VOICE_ID})


@app.route("/api/tts", methods=["POST"])
def api_tts():
    """Text to speech. The API key stays on the server.

    Errors are surfaced explicitly instead of returning silent audio: a mute
    assistant with a 200 response is the hardest thing to debug.
    """
    if TTS_PROVIDER == "browser":
        return jsonify({"error": "TTS_PROVIDER=browser", "use_browser": True}), 503
    if not ELEVEN_API_KEY:
        return jsonify({"error": "ELEVENLABS_API_KEY missing from .env", "use_browser": True}), 503
    text = (request.get_json(force=True) or {}).get("text", "").strip()
    if not text:
        return jsonify({"error": "empty text"}), 400

    # flash is the fastest; if the voice does not support it, fall back.
    for model in ("eleven_flash_v2_5", "eleven_multilingual_v2"):
        try:
            r = requests.post(
                f"https://api.elevenlabs.io/v1/text-to-speech/{ELEVEN_VOICE_ID}/stream",
                params={"output_format": "mp3_44100_128"},
                headers={"xi-api-key": ELEVEN_API_KEY, "Content-Type": "application/json"},
                json={
                    "text": text[:1200],
                    "model_id": model,
                    "voice_settings": {"stability": 0.5, "similarity_boost": 0.75},
                },
                timeout=30,
                stream=True,
                verify=VERIFY_SSL,
            )
            if r.status_code == 200:
                audio = r.content  # buffered: partial streams broke playback
                if len(audio) < 500:
                    raise ValueError(f"audio too small ({len(audio)} bytes)")
                return Response(audio, mimetype="audio/mpeg",
                                headers={"Content-Length": str(len(audio))})
            detail = r.text[:400]
            app.logger.warning("TTS %s -> %s: %s", model, r.status_code, detail)
            if r.status_code in (401, 403):
                # A 401 from ElevenLabs covers several very different problems.
                # The real cause lives in detail.status; surface it verbatim.
                status = ""
                try:
                    status = ((r.json().get("detail") or {}).get("status") or "")
                except Exception:  # noqa: BLE001
                    pass
                hints = {
                    "quota_exceeded":
                        "Character quota exhausted. Check your usage at elevenlabs.io; "
                        "the plan resets monthly.",
                    "detected_unusual_activity":
                        "ElevenLabs flagged unusual activity — this is common on free "
                        "tiers behind a VPN or a corporate proxy. Free TTS is disabled "
                        "until you upgrade or contact their support.",
                    "invalid_api_key":
                        "The key is wrong or was revoked. Regenerate it at "
                        "elevenlabs.io > profile > API Keys.",
                    "missing_permissions":
                        "The key lacks the text_to_speech permission. Recreate it with "
                        "that scope enabled.",
                }
                msg = hints.get(status, f"ElevenLabs rejected the request ({r.status_code}).")
                return jsonify({"error": msg, "eleven_status": status or None,
                                "detail": detail,
                                "use_browser": TTS_PROVIDER == "auto"}), 502
            if r.status_code == 422:
                continue  # voice/model mismatch: try the next model
            return jsonify({"error": f"ElevenLabs {r.status_code}: {detail}"}), 502
        except Exception as exc:  # noqa: BLE001
            app.logger.warning("TTS %s failed: %s", model, exc)
    return jsonify({"error": f"TTS unavailable for voice {ELEVEN_VOICE_ID}",
                    "use_browser": TTS_PROVIDER == "auto"}), 502


@app.route("/api/voice/diag")
def api_voice_diag():
    """One call that tells you exactly what is wrong with the voice setup."""
    out = {"key_present": bool(ELEVEN_API_KEY), "voice_id": ELEVEN_VOICE_ID,
           "agent_id": ELEVEN_AGENT_ID or None}
    if not ELEVEN_API_KEY:
        out["verdict"] = "ELEVENLABS_API_KEY is missing from .env"
        return jsonify(out), 503

    out["key_preview"] = ELEVEN_API_KEY[:6] + "..." + ELEVEN_API_KEY[-4:]
    out["key_length"] = len(ELEVEN_API_KEY)
    h = {"xi-api-key": ELEVEN_API_KEY}

    for label, url in (("user", "https://api.elevenlabs.io/v1/user"),
                       ("subscription", "https://api.elevenlabs.io/v1/user/subscription")):
        try:
            r = requests.get(url, headers=h, timeout=15, verify=VERIFY_SSL)
            out[label] = {"status": r.status_code}
            if r.ok:
                d = r.json()
                if label == "subscription":
                    used = d.get("character_count")
                    limit = d.get("character_limit")
                    out[label].update({
                        "tier": d.get("tier"),
                        "characters_used": used,
                        "character_limit": limit,
                        "remaining": (limit - used) if (limit is not None and used is not None) else None,
                    })
            else:
                out[label]["detail"] = r.text[:300]
        except Exception as exc:  # noqa: BLE001
            out[label] = {"error": str(exc)[:200]}

    # ¿La voz existe y es accesible con esta key?
    try:
        r = requests.get(f"https://api.elevenlabs.io/v1/voices/{ELEVEN_VOICE_ID}",
                         headers=h, timeout=15, verify=VERIFY_SSL)
        out["voice"] = ({"status": r.status_code, "name": r.json().get("name")}
                        if r.ok else {"status": r.status_code, "detail": r.text[:200]})
    except Exception as exc:  # noqa: BLE001
        out["voice"] = {"error": str(exc)[:200]}

    u = out.get("user", {}).get("status")
    if u == 200:
        rem = out.get("subscription", {}).get("remaining")
        if rem is not None and rem <= 0:
            out["verdict"] = "Key is valid but the character quota is exhausted."
        elif out.get("voice", {}).get("status") != 200:
            out["verdict"] = f"Key is valid but voice {ELEVEN_VOICE_ID} is not accessible."
        else:
            out["verdict"] = "Key, quota and voice all look fine."
    elif u in (401, 403):
        out["verdict"] = "The key itself is rejected: wrong, revoked, or missing scopes."
    else:
        out["verdict"] = "Could not reach the ElevenLabs API. Check network or proxy."
    return jsonify(out)


@app.route("/api/tts/test")
def api_tts_test():
    """Quick check: open this in the browser and you should hear the voice."""
    if not ELEVEN_API_KEY:
        return jsonify({"error": "ELEVENLABS_API_KEY missing"}), 503
    r = requests.post(
        f"https://api.elevenlabs.io/v1/text-to-speech/{ELEVEN_VOICE_ID}",
        headers={"xi-api-key": ELEVEN_API_KEY, "Content-Type": "application/json"},
        json={"text": "Terminal online. Voice check complete.",
              "model_id": "eleven_multilingual_v2"},
        timeout=30, verify=VERIFY_SSL,
    )
    if r.status_code != 200:
        return jsonify({"status": r.status_code, "detail": r.text[:400],
                        "voice_id": ELEVEN_VOICE_ID}), 502
    return Response(r.content, mimetype="audio/mpeg")


def indicator_series(bars: list[dict], which: str) -> dict:
    """Technical overlays computed in Python so the chart and the model always
    agree on the numbers. Returns {series: {name: [{time, value}]}, levels: []}.
    """
    if len(bars) < 25:
        return {"series": {}, "levels": []}
    closes = [b["close"] for b in bars]
    times = [b["time"] for b in bars]
    out: dict = {"series": {}, "levels": []}

    def rolling(fn, n):
        return [
            {"time": times[i], "value": round(fn(closes[i - n + 1 : i + 1]), 2)}
            for i in range(n - 1, len(closes))
        ]

    if which in ("sma20", "all"):
        out["series"]["sma20"] = rolling(lambda w: sum(w) / len(w), 20)
    if which in ("sma50", "all") and len(closes) >= 50:
        out["series"]["sma50"] = rolling(lambda w: sum(w) / len(w), 50)
    if which in ("ema12", "all"):
        k, e, pts = 2 / 13, sum(closes[:12]) / 12, []
        for i in range(12, len(closes)):
            e = closes[i] * k + e * (1 - k)
            pts.append({"time": times[i], "value": round(e, 2)})
        out["series"]["ema12"] = pts

    if which in ("bollinger", "all"):
        up, lo = [], []
        for i in range(19, len(closes)):
            w = closes[i - 19 : i + 1]
            m = sum(w) / 20
            sd = math.sqrt(sum((x - m) ** 2 for x in w) / 20)
            up.append({"time": times[i], "value": round(m + 2 * sd, 2)})
            lo.append({"time": times[i], "value": round(m - 2 * sd, 2)})
        out["series"]["bb_upper"], out["series"]["bb_lower"] = up, lo

    if which in ("vwap", "all"):
        cum_pv = cum_v = 0.0
        pts = []
        for b in bars[-60:]:
            tp = (b["high"] + b["low"] + b["close"]) / 3
            cum_pv += tp * (b["volume"] or 0)
            cum_v += b["volume"] or 0
            if cum_v:
                pts.append({"time": b["time"], "value": round(cum_pv / cum_v, 2)})
        out["series"]["vwap"] = pts

    if which in ("rsi", "all"):
        pts = []
        for i in range(14, len(closes)):
            w = closes[i - 14 : i + 1]
            g = sum(max(w[j] - w[j - 1], 0) for j in range(1, 15)) / 14
            l = sum(max(w[j - 1] - w[j], 0) for j in range(1, 15)) / 14
            v = 100.0 if l == 0 else 100 - 100 / (1 + g / l)
            pts.append({"time": times[i], "value": round(v, 1)})
        out["series"]["rsi14"] = pts

    if which in ("fib", "all"):
        w = closes[-120:] if len(closes) >= 120 else closes
        hi, lo_ = max(w), min(w)
        rng = hi - lo_
        out["levels"] += [
            {"label": f"Fib {int(r*1000)/10}%", "price": round(hi - rng * r, 2), "kind": "fib"}
            for r in (0.0, 0.236, 0.382, 0.5, 0.618, 0.786, 1.0)
        ]

    if which in ("levels", "all"):
        # Swing pivots: local extremes over a 5-bar window, clustered.
        w = bars[-120:]
        highs = [w[i]["high"] for i in range(2, len(w) - 2)
                 if w[i]["high"] == max(x["high"] for x in w[i - 2 : i + 3])]
        lows = [w[i]["low"] for i in range(2, len(w) - 2)
                if w[i]["low"] == min(x["low"] for x in w[i - 2 : i + 3])]
        last = closes[-1]
        res = sorted({round(h, 2) for h in highs if h > last})[:3]
        sup = sorted({round(l, 2) for l in lows if l < last}, reverse=True)[:3]
        out["levels"] += [{"label": "Resistance", "price": p, "kind": "res"} for p in res]
        out["levels"] += [{"label": "Support", "price": p, "kind": "sup"} for p in sup]

    return out


@app.route("/api/indicators/<symbol>")
def api_indicators(symbol):
    which = request.args.get("which", "all")
    tf = request.args.get("timeframe", "1Day")
    bars = get_bars(symbol.upper(), timeframe=tf, limit=250)["bars"]
    return jsonify({"symbol": symbol.upper(), **indicator_series(bars, which)})


# --------------------------------------------------------------------------
# Recommendation engine — combines chart signals with news tone
# --------------------------------------------------------------------------
POS_WORDS = ("beat", "beats", "surge", "surges", "rally", "rallies", "upgrade",
             "upgraded", "record", "jumps", "soars", "growth", "profit", "wins",
             "raises", "outperform", "bullish", "strong", "gains", "approval")
NEG_WORDS = ("miss", "misses", "plunge", "plunges", "slump", "downgrade", "cut",
             "cuts", "probe", "lawsuit", "recall", "warns", "warning", "falls",
             "drops", "layoff", "layoffs", "bearish", "weak", "loss", "losses",
             "investigation", "delay", "delays")


def news_tone(items: list[dict]) -> dict:
    """Crude but transparent headline scoring. Deliberately not an LLM call:
    it must be fast, free and reproducible."""
    pos = neg = 0
    drivers = []
    for it in items[:10]:
        t = (it.get("title") or "").lower()
        p = sum(1 for w in POS_WORDS if w in t)
        n = sum(1 for w in NEG_WORDS if w in t)
        if p > n:
            pos += 1
            drivers.append({"tone": "+", "title": it.get("title", "")[:110]})
        elif n > p:
            neg += 1
            drivers.append({"tone": "-", "title": it.get("title", "")[:110]})
    total = pos + neg
    if not total:
        label = "neutral"
    elif pos >= neg * 2:
        label = "positive"
    elif neg >= pos * 2:
        label = "negative"
    else:
        label = "mixed"
    return {"label": label, "positive": pos, "negative": neg,
            "drivers": drivers[:3], "headlines_scored": len(items[:10])}


def build_recommendation(symbol: str) -> dict:
    """Turns indicators + headlines into an explicit, auditable read.

    Every point of conviction traces back to a rule listed in `signals`, so the
    model never has to invent a rationale — it just reads this out.
    """
    a = compute_analysis(symbol)
    if a.get("error"):
        return {"symbol": symbol, "error": a["error"]}
    a.pop("_bars", None)

    price = a["last_close"]
    atr = a.get("atr14_pct")
    rsi = a.get("rsi14")
    signals, score = [], 0

    if a.get("trend") == "uptrend":
        score += 2
        signals.append("SMA20 above SMA50")
    elif a.get("trend") == "downtrend":
        score -= 2
        signals.append("SMA20 below SMA50")

    dev = a.get("price_vs_sma20_pct")
    if dev is not None:
        if dev > 0:
            score += 1
            signals.append(f"{dev}% above the 20-day")
        else:
            score -= 1
            signals.append(f"{abs(dev)}% below the 20-day")

    if rsi is not None:
        if rsi > 70:
            score -= 2
            signals.append(f"RSI {rsi}, overbought")
        elif rsi < 30:
            score += 2
            signals.append(f"RSI {rsi}, oversold")
        elif rsi > 55:
            score += 1
            signals.append(f"RSI {rsi}, momentum positive")
        elif rsi < 45:
            score -= 1
            signals.append(f"RSI {rsi}, momentum negative")

    pos52 = a.get("pos_in_52w_range_pct")
    if pos52 is not None:
        if pos52 > 90:
            score -= 1
            signals.append(f"{pos52}% of the 52-week range, near highs")
        elif pos52 < 15:
            score += 1
            signals.append(f"{pos52}% of the 52-week range, near lows")

    tone = news_tone(get_news(symbol, 10))
    score += {"positive": 2, "negative": -2, "mixed": 0, "neutral": 0}[tone["label"]]
    if tone["label"] in ("positive", "negative"):
        signals.append(f"headline tone {tone['label']}")

    if score >= 4:
        bias, conviction = "bullish", "high"
    elif score >= 2:
        bias, conviction = "bullish", "moderate"
    elif score <= -4:
        bias, conviction = "bearish", "high"
    elif score <= -2:
        bias, conviction = "bearish", "moderate"
    else:
        bias, conviction = "neutral", "low"

    rec = {
        "symbol": symbol,
        "as_of": a.get("as_of"),
        "data_source": a.get("data_source"),
        "price": price,
        "bias": bias,
        "conviction": conviction,
        "score": score,
        "signals": signals,
        "news_tone": tone["label"],
        "news_drivers": tone["drivers"],
    }
    if a.get("stale"):
        rec["stale"] = True
    # Levels sized off real volatility, not round numbers.
    # Explicit, actionable levels. HOLD when conviction does not justify a trade:
    # a recommendation engine that always has a trade is a broken one.
    rec["action"] = "HOLD"
    if atr:
        rec["atr_pct"] = atr
        band = price * atr / 100
        if bias == "bullish" and conviction in ("moderate", "high"):
            rec["action"] = "BUY"
            rec["buy_point"] = round(price - band * 0.25, 2)   # slight pullback entry
            rec["stop_loss"] = round(price - band * 1.5, 2)
            rec["sell_point"] = round(price + band * 3.0, 2)
            rec["risk_reward"] = round((band * 3.0) / (band * 1.5), 2)
        elif bias == "bearish" and conviction in ("moderate", "high"):
            rec["action"] = "SELL"
            rec["sell_point"] = round(price + band * 0.25, 2)  # bounce to exit into
            rec["stop_loss"] = round(price + band * 1.5, 2)
            rec["buy_point"] = round(price - band * 3.0, 2)    # where it becomes interesting again
            rec["risk_reward"] = round((band * 3.0) / (band * 1.5), 2)
        else:
            rec["hold_reason"] = (
                f"signals conflict (score {score}); no edge worth the {atr}% daily range"
            )
            rec["revisit_above"] = round(price + band * 2, 2)
            rec["revisit_below"] = round(price - band * 2, 2)
    else:
        rec["hold_reason"] = "not enough history to size levels"
    return rec


# Sector map for the most common names. Alpaca's asset payload has no sector
# field, so this is a curated lookup — honest about being partial.
SECTORS = {
    "AAPL": "Technology", "MSFT": "Technology", "NVDA": "Technology",
    "GOOGL": "Technology", "GOOG": "Technology", "META": "Technology",
    "AMD": "Technology", "INTC": "Technology", "AVGO": "Technology",
    "CRM": "Technology", "ORCL": "Technology", "ADBE": "Technology",
    "CSCO": "Technology", "QCOM": "Technology", "TXN": "Technology",
    "AMZN": "Consumer Discretionary", "TSLA": "Consumer Discretionary",
    "HD": "Consumer Discretionary", "MCD": "Consumer Discretionary",
    "NKE": "Consumer Discretionary", "SBUX": "Consumer Discretionary",
    "JPM": "Financials", "BAC": "Financials", "GS": "Financials",
    "WFC": "Financials", "MS": "Financials", "V": "Financials",
    "MA": "Financials", "BRK.B": "Financials", "AXP": "Financials",
    "JNJ": "Healthcare", "UNH": "Healthcare", "PFE": "Healthcare",
    "ABBV": "Healthcare", "MRK": "Healthcare", "LLY": "Healthcare",
    "TMO": "Healthcare", "ABT": "Healthcare",
    "XOM": "Energy", "CVX": "Energy", "COP": "Energy", "SLB": "Energy",
    "PG": "Consumer Staples", "KO": "Consumer Staples", "PEP": "Consumer Staples",
    "WMT": "Consumer Staples", "COST": "Consumer Staples",
    "BA": "Industrials", "CAT": "Industrials", "GE": "Industrials",
    "UPS": "Industrials", "HON": "Industrials", "LMT": "Industrials",
    "NEE": "Utilities", "DUK": "Utilities", "SO": "Utilities",
    "AMT": "Real Estate", "PLD": "Real Estate", "SPG": "Real Estate",
    "LIN": "Materials", "SHW": "Materials", "FCX": "Materials",
    "DIS": "Communication", "NFLX": "Communication", "T": "Communication",
    "VZ": "Communication", "CMCSA": "Communication",
}
BROAD_ETFS = {"SPY", "VOO", "IVV", "VTI", "QQQ", "DIA", "IWM", "VT", "ACWI"}
BOND_ETFS = {"AGG", "BND", "TLT", "IEF", "SHY", "LQD", "TIP"}
INTL_ETFS = {"VXUS", "VEA", "VWO", "EFA", "IEMG", "EEM"}

GAP_SUGGESTIONS = [
    ("broad market core", BROAD_ETFS, "VOO",
     "A broad index fund anchors the portfolio so single-name risk matters less."),
    ("bonds", BOND_ETFS, "AGG",
     "Bond exposure cushions equity drawdowns; you currently have none."),
    ("international", INTL_ETFS, "VXUS",
     "Everything you hold is US-listed equity; international adds a different cycle."),
]


def classify(sym: str) -> str:
    if sym in BROAD_ETFS:
        return "Broad ETF"
    if sym in BOND_ETFS:
        return "Bonds"
    if sym in INTL_ETFS:
        return "International"
    return SECTORS.get(sym, "Unclassified")


def build_diversification(symbols: list[str]) -> dict:
    """Concentration read plus the single most useful gap to fill.

    Uses HHI (Herfindahl index) on equal-weighted buckets: with no position
    sizes available, every holding counts the same.
    """
    if not symbols:
        return {"score": 0, "verdict": "empty watchlist", "buckets": {}, "gaps": []}

    buckets: dict[str, int] = {}
    for s in symbols:
        buckets[classify(s)] = buckets.get(classify(s), 0) + 1

    n = len(symbols)
    hhi = sum((c / n) ** 2 for c in buckets.values())
    # HHI 1.0 = everything in one bucket; 1/k = perfectly spread over k buckets.
    score = round(max(0.0, min(1.0, (1 - hhi) / (1 - 1 / max(len(buckets), 2)))) * 100)

    if len(buckets) == 1:
        verdict = f"fully concentrated in {next(iter(buckets))}"
    elif score >= 70:
        verdict = f"well spread across {len(buckets)} groups"
    elif score >= 40:
        verdict = f"moderately concentrated across {len(buckets)} groups"
    else:
        verdict = f"heavily concentrated across {len(buckets)} groups"

    top = max(buckets.items(), key=lambda kv: kv[1])
    gaps = []
    if top[1] / n >= 0.5 and len(symbols) > 2:
        gaps.append({"issue": f"{round(top[1]/n*100)}% sits in {top[0]}",
                     "suggest": None,
                     "why": "One sector shock would move most of the list at once."})
    held = set(symbols)
    for label, family, pick, why in GAP_SUGGESTIONS:
        if not (held & family):
            gaps.append({"issue": f"no {label} exposure", "suggest": pick, "why": why})

    return {"score": score, "verdict": verdict, "buckets": buckets,
            "holdings": n, "gaps": gaps[:3]}


@app.route("/api/diversification")
def api_diversification():
    syms = request.args.get("symbols", ",".join(DEFAULT_SYMBOLS))
    return jsonify(build_diversification([s.strip().upper() for s in syms.split(",") if s.strip()]))


def build_simulation(amount: float, symbols: list[str]) -> dict:
    """Allocates capital by inverse volatility and projects it forward.

    Inverse-vol weighting means calmer assets get more money, which is the
    standard naive risk-parity approach. Returns are drawn from each symbol's
    own history and hard-capped: extrapolating a hot streak for ten years is
    how simulators end up lying.
    """
    stats = {}
    for sym in symbols[:10]:
        a = compute_analysis(sym)
        bars = a.pop("_bars", [])
        if a.get("error") or len(bars) < 60:
            continue
        closes = [b["close"] for b in bars]
        years = len(closes) / 252
        cagr = ((closes[-1] / closes[0]) ** (1 / years) - 1) if years > 0.5 and closes[0] else 0.0
        cagr = max(min(cagr, 0.25), -0.15)          # sanity cap
        vol = (a.get("annualized_vol_pct") or 25) / 100
        stats[sym] = {"price": a["last_close"], "cagr": cagr, "vol": max(vol, 0.05),
                      "source": a.get("data_source")}

    if not stats:
        return {"error": "no usable price history for these symbols"}

    inv = {s: 1 / v["vol"] for s, v in stats.items()}
    tot = sum(inv.values())
    alloc = []
    for sym, v in stats.items():
        w = inv[sym] / tot
        cash = amount * w
        alloc.append({
            "symbol": sym, "weight_pct": round(w * 100, 1),
            "amount": round(cash, 2), "price": v["price"],
            "shares": round(cash / v["price"], 2),
            "assumed_cagr_pct": round(v["cagr"] * 100, 1),
            "annualized_vol_pct": round(v["vol"] * 100, 1),
        })

    port_cagr = sum(stats[a["symbol"]]["cagr"] * a["weight_pct"] / 100 for a in alloc)
    port_vol = math.sqrt(sum((a["weight_pct"] / 100) ** 2 *
                             stats[a["symbol"]]["vol"] ** 2 for a in alloc))
    # Correlation is unknown, so widen the band: independence would understate risk.
    port_vol = min(port_vol * 1.6, 0.45)

    horizons = []
    for yrs in (2, 5, 10):
        median = amount * ((1 + port_cagr) ** yrs)
        spread = port_vol * math.sqrt(yrs)
        horizons.append({
            "years": yrs,
            "median": round(median, 2),
            "low": round(median * math.exp(-spread), 2),
            "high": round(median * math.exp(spread), 2),
            "total_return_pct": round((median / amount - 1) * 100, 1),
        })

    return {
        "invested": round(amount, 2),
        "allocation": alloc,
        "method": "inverse volatility weighting",
        "portfolio_cagr_pct": round(port_cagr * 100, 2),
        "portfolio_vol_pct": round(port_vol * 100, 1),
        "horizons": horizons,
        "diversification": build_diversification(list(stats.keys())),
        "caveat": ("Past drift projected forward with a volatility band. Not a "
                   "forecast: real returns depend on events no model has seen."),
    }


@app.route("/api/simulate", methods=["POST"])
def api_simulate():
    d = request.get_json(force=True) or {}
    try:
        amount = float(d.get("amount", 0))
    except (TypeError, ValueError):
        return jsonify({"error": "invalid amount"}), 400
    if amount <= 0:
        return jsonify({"error": "amount must be positive"}), 400
    syms = d.get("symbols") or DEFAULT_SYMBOLS
    return jsonify(build_simulation(amount, [s.upper() for s in syms]))


def build_briefing(symbols: list[str]) -> dict:
    """Scans the watchlist and surfaces only what is worth interrupting for."""
    snaps = get_snapshots(symbols)
    alerts = []
    for sym in symbols[:8]:
        q = snaps.get(sym) or {}
        chg = q.get("change_pct")
        if chg is not None and abs(chg) >= 2:
            alerts.append({"symbol": sym, "kind": "move", "urgency": abs(chg),
                           "text": f"{sym} {'up' if chg > 0 else 'down'} {abs(chg)}% today"})
        a = compute_analysis(sym)
        a.pop("_bars", None)
        rsi = a.get("rsi14")
        if rsi is not None and (rsi > 72 or rsi < 28):
            alerts.append({"symbol": sym, "kind": "rsi", "urgency": abs(rsi - 50) / 10,
                           "text": f"{sym} RSI {rsi}, "
                                   f"{'overbought' if rsi > 72 else 'oversold'}"})
    alerts.sort(key=lambda x: -x["urgency"])
    return {"alerts": alerts[:3], "scanned": len(symbols),
            "quotes": [v for v in snaps.values()]}


@app.route("/api/recommendation/<symbol>")
def api_recommendation(symbol):
    return jsonify(build_recommendation(symbol.upper()))


@app.route("/api/briefing")
def api_briefing():
    syms = request.args.get("symbols", ",".join(DEFAULT_SYMBOLS))
    return jsonify(build_briefing([s.strip().upper() for s in syms.split(",") if s.strip()]))


@app.route("/api/bars/<symbol>")
def api_bars(symbol):
    tf = request.args.get("timeframe", "1Day")
    limit = min(int(request.args.get("limit", 250)), 2000)
    payload = get_bars(symbol.upper(), timeframe=tf, limit=limit)
    return jsonify({"symbol": symbol.upper(), **payload})


@app.route("/api/quotes")
def api_quotes():
    syms = request.args.get("symbols", ",".join(DEFAULT_SYMBOLS))
    lst = [s.strip().upper() for s in syms.split(",") if s.strip()]
    _tracked.update(lst)
    return jsonify(list(get_snapshots(lst).values()))


@app.route("/api/analysis/<symbol>")
def api_analysis(symbol):
    a = compute_analysis(symbol.upper(), request.args.get("timeframe", "1Day"))
    a.pop("_bars", None)
    return jsonify(a)


@app.route("/api/validate/<symbol>")
def api_validate(symbol):
    sym = symbol.upper()
    match = next((a for a in search_assets(sym, 3) if a["symbol"] == sym), None)
    snap = get_snapshots([sym]).get(sym)
    if match or (snap and snap["price"] > 0 and snap["source"] == "alpaca"):
        _tracked.add(sym)
        return jsonify({"exists": True, "symbol": sym,
                        "name": match["name"] if match else sym})
    return jsonify({"exists": False}), 404


@app.route("/api/news")
def api_news():
    topic = request.args.get("topic")
    if topic:
        items = get_news_by_topic(topic) or get_news(request.args.get("symbol"))
    else:
        items = get_news(request.args.get("symbol"))
    kw = request.args.get("keywords")
    if kw:
        items = filter_news_by_keywords(items, kw.split(","))
    return jsonify(items)


@app.route("/api/whatif", methods=["POST"])
def api_whatif():
    d = request.get_json(force=True)
    sym = d.get("symbol", "AAPL").upper()
    bars = get_bars(sym, limit=120)["bars"]
    pts = build_projection(
        bars,
        days=int(d.get("days", 10)),
        scenario=d.get("scenario", "base"),
        shock_pct=float(d.get("shock_pct", d.get("magnitude", 0))),
    )
    return jsonify({"symbol": sym, "label": d.get("label", "Scenario"), "points": pts})


@app.route("/api/chat", methods=["POST"])
def api_chat():
    d = request.get_json(force=True)
    return jsonify(
        ask_ai(
            d.get("message", ""),
            d.get("symbol", "AAPL").upper(),
            d.get("session_id", "default"),
        )
    )


@app.route("/api/health")
def api_health():
    ok_alpaca = get_snapshots(["SPY"]).get("SPY", {}).get("source") == "alpaca"
    return jsonify({"alpaca": ok_alpaca, "feed": ALPACA_FEED, "model": LLM_MODEL,
                    "subscribers": len(_subscribers), "assets": len(load_assets()),
                    "voice": bool(ELEVEN_API_KEY and ELEVEN_AGENT_ID)})


@app.route("/")
def index():
    # Read on every request: you can edit index.html without restarting Flask.
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "index.html")
    with open(path, encoding="utf-8") as f:
        return Response(f.read(), mimetype="text/html")


if __name__ == "__main__":
    missing = [n for n, v in [
        ("ALPACA_KEY_ID", ALPACA_KEY_ID), ("ALPACA_SECRET_KEY", ALPACA_SECRET_KEY),
        ("LLM_API_KEY", LLM_API_KEY), ("ELEVENLABS_API_KEY", ELEVEN_API_KEY),
        ("ELEVENLABS_AGENT_ID", ELEVEN_AGENT_ID)] if not v]
    if missing:
        print("WARNING: missing variables in .env -> " + ", ".join(missing))
    else:
        print("Config loaded. Alpaca:", ALPACA_KEY_ID[:4] + "...", "| feed:", ALPACA_FEED)
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)),
            debug=False, threaded=True)
